export const LoaderConfig = {

    greenCircle: "src/sprites/Green-Circle.png",
    redCircle:"src/sprites/Red-Circle.png",

    greenBackground: "src/sprites/greenBg.jpg",
    redBackground: "src/sprites/redBg.jpg",
    greenRightBorder: "src/sprites/greenRightBorder.png",
    greenLeftBorder: "src/sprites/greenLeftborder.png",
    redRightBorder: "src/sprites/redRightBorder.png",
    redLeftBorder: "src/sprites/redLeftborder.png",

    greenHead: "src/sprites/greenHead.png",
    redHead: "src/sprites/redHead.png",

    greenLogo: "src/sprites/cash-machine-logo.png",
    redLogo: "src/sprites/redcash-machine-logo.png",
    taskBar: "src/sprites/taskBar.png",
    greenCentreFrame: "src/sprites/greenCentreFrame.png",
    redCentreFrame: "src/sprites/redCentreFrame.png",
    whatUSeeText: "src/sprites/winwhatuSeeText.png",
    slotBg: "src/sprites/SlotBg.png",
    centerOverLay: "src/sprites/middleLayer.png",
    rightOverLay: "src/sprites/rightOverLay.png",
    AutoSpinCountBg: "src/sprites/AutoSpinCountBg.png",


    spinBtn : "/src/sprites/ButtonSpin_1.png",
    spinBtnOnPressed :  "/src/sprites/ButtonSpinHover_1.png",
    maxBetBtn :  "/src/sprites/ButtonMaxBet_1.png",
    maxBetBtOnPressed :  "/src/sprites/ButtonMaxBetHover_1.png",
    autoSpin :  "/src/sprites/ButtonAutoSpin_1.png",
    autoSpinOnPressed : "/src/sprites/ButtonAutoSpinHover_1.png",
    pBtn  :  "/src/sprites/ButtonPlus.png",
    pBtnH  :  "/src/sprites/ButtonPlusHover.png",
    mBtn: "src/sprites/ButtonMinus.png",
    mBtnH: "src/sprites/ButtonMinusHover.png",

    MenuBtn :  "/src/sprites/ButtonMenu.png",
    MenuBtnH :  "/src/sprites/ButtonMenuHover.png",
    settingBtn :  "/src/sprites/ButtonSettings.png",
    settingBtnH :  "/src/sprites/ButtonSettingsHover.png",
    infoBtn :  "/src/sprites/ButtonInfo.png",
    infoBtnH :  "/src/sprites/ButtonInfoHover.png",
    volumneSpeaker: "src/sprites/volumneSpeaker.png",
    volumneSpeakerH: "src/sprites/volumneSpeakerHover.png",
    betCoins: "src/sprites/betCoins.png",
    betCoinsH: "src/sprites/betCoinsHover.png",
    mutedSpeaker: "src/sprites/mutedSpeaker.png",
    bgPurple:"src/sprites/BgPurple.png",
    playButtonBg: "src/sprites/playButtonBg.png",
    largePlayBg: "src/sprites/largePlay.png",
    largePlayHover : "src/sprites/largePlayHover.png",
    largePlayClicked: "src/sprites/largePlayClicked.png",
    PlayTriangle: "src/sprites/PlayTriangle.png",
    smallPlayBg: "src/sprites/smallButton.png", 
    smallPlayBgHover: "src/sprites/smallButtonHover.png",
    bgAutoSpin: "src/sprites/BgAutoSpin.png",
    zeroBetBtn: "src/sprites/zeroBetBtn.png",
    zeroHoverBetBtn: "src/sprites/zeroHoverBetBtn.png",
    tenBetBtn: "src/sprites/tenBetBtn.png",
    tenHoverBetBtn: "src/sprites/tenHoverBetBtn.png",
    TwentyFiveBetBtn: "src/sprites/TwentyFiveBetBtn.png",
    TwentyFiveHoverBetBtn: "src/sprites/TwentyFiveHoverBetBtn.png",
    FiftyBetBtn: "src/sprites/FiftyBetBtn.png",
    FiftyHoverBetBtn: "src/sprites/fiftyHoverBetBtn.png",
    HundredBetBtn: "src/sprites/HundredBetBtn.png",
    HundredHoverBetBtn: "src/sprites/HundredHoverBetBtn.png",
    betArrow: "src/sprites/betArrow.png",
    autoSpinCircle: "src/sprites/autoSpinOuter.png",
    InfoPopupBg: "src/sprites/infoBg.png",
    payHelp: "src/sprites/PayHelp.png",
    winningSample: "src/sprites/winningSample1.png",
    winningSampleTwo: "src/sprites/winningSample2.png",
    gameRules: "src/sprites/gameRules.png",
    additionalInfoHeading: "src/sprites/AdditionalInfo.png",
    ArrowWithOption: "src/sprites/ArrowWithOption.png",
    spinPlay: "src/sprites/spinPlay.png",
    soundonOff: "src/sprites/soundOnOff.png",
    scrollerView: "src/sprites/scrollerView.png",
    scrollerViewBg: "src/sprites/scrollerViewBg.png",
    autoSpinHeading: "src/sprites/AutoSpinHeading.png",
    SettingHeading: "src/sprites/SettingHeading.png",
    betSettingsHeading: "src/sprites/betSettingsHeading.png",

    exitButton: "src/sprites/ExitButton.png",
    exitButtonPressed: "src/sprites/ExitButton.png",
    messagePopup: "src/sprites/messagePopup.png",

    musicImage: "src/sprites/Music.png",
    yesButton:"src/sprites/yesButton.png",
    noButton:"src/sprites/noButton.png",
    sounProgress: "src/sprites/soundProgreesBar.png",
    indicatorSprite: "src/sprites/SliderButton.png",

    greenCircleWinning: "src/sprites/greenCircleOverLay.png",
    redCircleWinning: "src/sprites/redCircleOverLay.png",
    greenCenterWinning: "src/sprites/greenCenterWinningLayer.png",
    redCenterWinning: "src/sprites/redCenterWinningLayer.png",

    greenslots0_1 :  "/src/sprites/Symbols/icon1/slots1_2.png",
    greenslots0_0: "/src/sprites/Symbols/icon1/slots1_1.png",
    greenslots0_2: "/src/sprites/Symbols/icon1/slots1_0.png",
    //red
    redslots0_0 : "/src/sprites/Symbols/iconred1/slots1_0.png",
    redslots0_1: "/src/sprites/Symbols/iconred1/slots1_1.png",
    redslots0_2: "/src/sprites/Symbols/iconred1/slots1_2.png",

    greenslots1_0 :  "/src/sprites/Symbols/icon2/1_00.png",
    greenslots1_1 :  "/src/sprites/Symbols/icon2/1_01.png",
    greenslots1_2 :  "/src/sprites/Symbols/icon2/1_02.png",
    greenslots1_3 :  "/src/sprites/Symbols/icon2/1_03.png",
    greenslots1_4 :  "/src/sprites/Symbols/icon2/1_04.png",
    greenslots1_5 :  "/src/sprites/Symbols/icon2/1_05.png",
    greenslots1_6 :  "/src/sprites/Symbols/icon2/1_06.png",
    greenslots1_7 :  "/src/sprites/Symbols/icon2/1_07.png",
    greenslots1_8 :  "/src/sprites/Symbols/icon2/1_08.png",
    greenslots1_9 :  "/src/sprites/Symbols/icon2/1_09.png",
    greenslots1_10 :  "/src/sprites/Symbols/icon2/1_10.png",
    greenslots1_11 :  "/src/sprites/Symbols/icon2/1_11.png",
    greenslots1_12 :  "/src/sprites/Symbols/icon2/1_12.png",
    greenslots1_13 :  "/src/sprites/Symbols/icon2/1_13.png",
    greenslots1_14 :  "/src/sprites/Symbols/icon2/1_14.png",
    greenslots1_15 :  "/src/sprites/Symbols/icon2/1_15.png",
    greenslots1_16 :  "/src/sprites/Symbols/icon2/1_16.png",
    greenslots1_17 :  "/src/sprites/Symbols/icon2/1_17.png",
    greenslots1_18 :  "/src/sprites/Symbols/icon2/1_18.png",
    greenslots1_19 :  "/src/sprites/Symbols/icon2/1_19.png",
    greenslots1_20 :  "/src/sprites/Symbols/icon2/1_20.png",
    greenslots1_21 :  "/src/sprites/Symbols/icon2/1_21.png",
    greenslots1_22 :  "/src/sprites/Symbols/icon2/1_22.png",
    greenslots1_23 :  "/src/sprites/Symbols/icon2/1_23.png",
    greenslots1_24 :  "/src/sprites/Symbols/icon2/1_24.png",
    greenslots1_25 :  "/src/sprites/Symbols/icon2/1_25.png",
    greenslots1_26 :  "/src/sprites/Symbols/icon2/1_26.png",
    greenslots1_27 :  "/src/sprites/Symbols/icon2/1_27.png",
    greenslots1_28 :  "/src/sprites/Symbols/icon2/1_28.png",
    greenslots1_29 :  "/src/sprites/Symbols/icon2/1_29.png",
    greenslots1_30 :  "/src/sprites/Symbols/icon2/1_30.png",
    greenslots1_31 :  "/src/sprites/Symbols/icon2/1_31.png",
    greenslots1_32 :  "/src/sprites/Symbols/icon2/1_32.png",
    greenslots1_33 :  "/src/sprites/Symbols/icon2/1_33.png",
    greenslots1_34 :  "/src/sprites/Symbols/icon2/1_34.png",
    greenslots1_35 :  "/src/sprites/Symbols/icon2/1_35.png",
    greenslots1_36 :  "/src/sprites/Symbols/icon2/1_36.png",

    redslots1_0 :  "/src/sprites/Symbols/iconred2/100.png",
    redslots1_1 :  "/src/sprites/Symbols/iconred2/101.png",
    redslots1_2 :  "/src/sprites/Symbols/iconred2/102.png",
    redslots1_3 :  "/src/sprites/Symbols/iconred2/103.png",
    redslots1_4 :  "/src/sprites/Symbols/iconred2/104.png",
    redslots1_5 :  "/src/sprites/Symbols/iconred2/105.png",
    redslots1_6 :  "/src/sprites/Symbols/iconred2/106.png",
    redslots1_7 :  "/src/sprites/Symbols/iconred2/107.png",
    redslots1_8 :  "/src/sprites/Symbols/iconred2/108.png",
    redslots1_9 :  "/src/sprites/Symbols/iconred2/109.png",
    redslots1_10 :  "/src/sprites/Symbols/iconred2/110.png",
    redslots1_11 :  "/src/sprites/Symbols/iconred2/111.png",
    redslots1_12 :  "/src/sprites/Symbols/iconred2/112.png",
    redslots1_13 :  "/src/sprites/Symbols/iconred2/113.png",
    redslots1_14 :  "/src/sprites/Symbols/iconred2/114.png",
    redslots1_15 :  "/src/sprites/Symbols/iconred2/115.png",
    redslots1_16 :  "/src/sprites/Symbols/iconred2/116.png",
    redslots1_17 :  "/src/sprites/Symbols/iconred2/117.png",
    redslots1_18 :  "/src/sprites/Symbols/iconred2/118.png",
    redslots1_19 :  "/src/sprites/Symbols/iconred2/119.png",
    redslots1_20 :  "/src/sprites/Symbols/iconred2/120.png",
    redslots1_21 :  "/src/sprites/Symbols/iconred2/121.png",
    redslots1_22 :  "/src/sprites/Symbols/iconred2/122.png",
    redslots1_23 :  "/src/sprites/Symbols/iconred2/123.png",
    redslots1_24 :  "/src/sprites/Symbols/iconred2/124.png",
    redslots1_25 :  "/src/sprites/Symbols/iconred2/125.png",
    redslots1_26 :  "/src/sprites/Symbols/iconred2/126.png",
    redslots1_27 :  "/src/sprites/Symbols/iconred2/127.png",
    redslots1_28 :  "/src/sprites/Symbols/iconred2/128.png",
    redslots1_29 :  "/src/sprites/Symbols/iconred2/129.png",
    redslots1_30 :  "/src/sprites/Symbols/iconred2/130.png",
    redslots1_31 :  "/src/sprites/Symbols/iconred2/131.png",
    redslots1_32 :  "/src/sprites/Symbols/iconred2/132.png",
    redslots1_33 :  "/src/sprites/Symbols/iconred2/133.png",
    redslots1_34 :  "/src/sprites/Symbols/iconred2/134.png",
    redslots1_35 :  "/src/sprites/Symbols/iconred2/135.png",
    redslots1_36 :  "/src/sprites/Symbols/iconred2/136.png",

    greenslots2_0 :  "/src/sprites/Symbols/icon3/2_00.png",
    greenslots2_1 :  "/src/sprites/Symbols/icon3/2_01.png",
    greenslots2_2 :  "/src/sprites/Symbols/icon3/2_02.png",
    greenslots2_3 :  "/src/sprites/Symbols/icon3/2_03.png",
    greenslots2_4 :  "/src/sprites/Symbols/icon3/2_04.png",
    greenslots2_5 :  "/src/sprites/Symbols/icon3/2_05.png",
    greenslots2_6 :  "/src/sprites/Symbols/icon3/2_06.png",
    greenslots2_7 :  "/src/sprites/Symbols/icon3/2_07.png",
    greenslots2_8 :  "/src/sprites/Symbols/icon3/2_08.png",
    greenslots2_9 :  "/src/sprites/Symbols/icon3/2_09.png",
    greenslots2_10 :  "/src/sprites/Symbols/icon3/2_10.png",
    greenslots2_11 :  "/src/sprites/Symbols/icon3/2_11.png",
    greenslots2_12 :  "/src/sprites/Symbols/icon3/2_12.png",
    greenslots2_13 :  "/src/sprites/Symbols/icon3/2_13.png",
    greenslots2_14 :  "/src/sprites/Symbols/icon3/2_14.png",
    greenslots2_15 :  "/src/sprites/Symbols/icon3/2_15.png",
    greenslots2_16 :  "/src/sprites/Symbols/icon3/2_16.png",
    greenslots2_17 :  "/src/sprites/Symbols/icon3/2_17.png",
    greenslots2_18 :  "/src/sprites/Symbols/icon3/2_18.png",
    greenslots2_19 :  "/src/sprites/Symbols/icon3/2_19.png",
    greenslots2_20 :  "/src/sprites/Symbols/icon3/2_20.png",
    greenslots2_21 :  "/src/sprites/Symbols/icon3/2_21.png",
    greenslots2_22 :  "/src/sprites/Symbols/icon3/2_22.png",
    greenslots2_23 :  "/src/sprites/Symbols/icon3/2_23.png",
    greenslots2_24 :  "/src/sprites/Symbols/icon3/2_24.png",
    greenslots2_25 :  "/src/sprites/Symbols/icon3/2_25.png",
    greenslots2_26 :  "/src/sprites/Symbols/icon3/2_26.png",
    greenslots2_27 :  "/src/sprites/Symbols/icon3/2_27.png",
    greenslots2_28 :  "/src/sprites/Symbols/icon3/2_28.png",
    greenslots2_29 :  "/src/sprites/Symbols/icon3/2_29.png",
    greenslots2_30 :  "/src/sprites/Symbols/icon3/2_30.png",
    greenslots2_31 :  "/src/sprites/Symbols/icon3/2_31.png",
    greenslots2_32 :  "/src/sprites/Symbols/icon3/2_32.png",
    greenslots2_33 :  "/src/sprites/Symbols/icon3/2_33.png",
    greenslots2_34 :  "/src/sprites/Symbols/icon3/2_34.png",
    greenslots2_35 :  "/src/sprites/Symbols/icon3/2_35.png",
    greenslots2_36 :  "/src/sprites/Symbols/icon3/2_36.png",

    redslots2_0 :  "/src/sprites/Symbols/iconred3/200.png",
    redslots2_1 :  "/src/sprites/Symbols/iconred3/201.png",
    redslots2_2 :  "/src/sprites/Symbols/iconred3/202.png",
    redslots2_3 :  "/src/sprites/Symbols/iconred3/203.png",
    redslots2_4 :  "/src/sprites/Symbols/iconred3/204.png",
    redslots2_5 :  "/src/sprites/Symbols/iconred3/205.png",
    redslots2_6 :  "/src/sprites/Symbols/iconred3/206.png",
    redslots2_7 :  "/src/sprites/Symbols/iconred3/207.png",
    redslots2_8 :  "/src/sprites/Symbols/iconred3/208.png",
    redslots2_9 :  "/src/sprites/Symbols/iconred3/209.png",
    redslots2_10 :  "/src/sprites/Symbols/iconred3/210.png",
    redslots2_11 :  "/src/sprites/Symbols/iconred3/211.png",
    redslots2_12 :  "/src/sprites/Symbols/iconred3/212.png",
    redslots2_13 :  "/src/sprites/Symbols/iconred3/213.png",
    redslots2_14 :  "/src/sprites/Symbols/iconred3/214.png",
    redslots2_15 :  "/src/sprites/Symbols/iconred3/215.png",
    redslots2_16 :  "/src/sprites/Symbols/iconred3/216.png",
    redslots2_17 :  "/src/sprites/Symbols/iconred3/217.png",
    redslots2_18 :  "/src/sprites/Symbols/iconred3/218.png",
    redslots2_19 :  "/src/sprites/Symbols/iconred3/219.png",
    redslots2_20 :  "/src/sprites/Symbols/iconred3/220.png",
    redslots2_21 :  "/src/sprites/Symbols/iconred3/221.png",
    redslots2_22 :  "/src/sprites/Symbols/iconred3/222.png",
    redslots2_23 :  "/src/sprites/Symbols/iconred3/223.png",
    redslots2_24 :  "/src/sprites/Symbols/iconred3/224.png",
    redslots2_25 :  "/src/sprites/Symbols/iconred3/225.png",
    redslots2_26 :  "/src/sprites/Symbols/iconred3/226.png",
    redslots2_27 :  "/src/sprites/Symbols/iconred3/227.png",
    redslots2_28 :  "/src/sprites/Symbols/iconred3/228.png",
    redslots2_29 :  "/src/sprites/Symbols/iconred3/229.png",
    redslots2_30 :  "/src/sprites/Symbols/iconred3/230.png",
    redslots2_31 :  "/src/sprites/Symbols/iconred3/231.png",
    redslots2_32 :  "/src/sprites/Symbols/iconred3/232.png",
    redslots2_33 :  "/src/sprites/Symbols/iconred3/233.png",
    redslots2_34 :  "/src/sprites/Symbols/iconred3/234.png",
    redslots2_35 :  "/src/sprites/Symbols/iconred3/235.png",
    redslots2_36 :  "/src/sprites/Symbols/iconred3/236.png",

    greenslots3_0 :  "/src/sprites/Symbols/icon4/5_00.png",
    greenslots3_1 :  "/src/sprites/Symbols/icon4/5_01.png",
    greenslots3_2 :  "/src/sprites/Symbols/icon4/5_02.png",
    greenslots3_3 :  "/src/sprites/Symbols/icon4/5_03.png",
    greenslots3_4 :  "/src/sprites/Symbols/icon4/5_04.png",
    greenslots3_5 :  "/src/sprites/Symbols/icon4/5_05.png",
    greenslots3_6 :  "/src/sprites/Symbols/icon4/5_06.png",
    greenslots3_7 :  "/src/sprites/Symbols/icon4/5_07.png",
    greenslots3_8 :  "/src/sprites/Symbols/icon4/5_08.png",
    greenslots3_9 :  "/src/sprites/Symbols/icon4/5_09.png",
    greenslots3_10 :  "/src/sprites/Symbols/icon4/5_10.png",
    greenslots3_11 :  "/src/sprites/Symbols/icon4/5_11.png",
    greenslots3_12 :  "/src/sprites/Symbols/icon4/5_12.png",
    greenslots3_13 :  "/src/sprites/Symbols/icon4/5_13.png",
    greenslots3_14 :  "/src/sprites/Symbols/icon4/5_14.png",
    greenslots3_15 :  "/src/sprites/Symbols/icon4/5_15.png",
    greenslots3_16 :  "/src/sprites/Symbols/icon4/5_16.png",
    greenslots3_17 :  "/src/sprites/Symbols/icon4/5_17.png",
    greenslots3_18 :  "/src/sprites/Symbols/icon4/5_18.png",
    greenslots3_19 :  "/src/sprites/Symbols/icon4/5_19.png",
    greenslots3_20 :  "/src/sprites/Symbols/icon4/5_20.png",
    greenslots3_21 :  "/src/sprites/Symbols/icon4/5_21.png",
    greenslots3_22 :  "/src/sprites/Symbols/icon4/5_22.png",
    greenslots3_23 :  "/src/sprites/Symbols/icon4/5_23.png",
    greenslots3_24 :  "/src/sprites/Symbols/icon4/5_24.png",
    greenslots3_25 :  "/src/sprites/Symbols/icon4/5_25.png",
    greenslots3_26 :  "/src/sprites/Symbols/icon4/5_26.png",
    greenslots3_27 :  "/src/sprites/Symbols/icon4/5_27.png",
    greenslots3_28 :  "/src/sprites/Symbols/icon4/5_28.png",
    greenslots3_29 :  "/src/sprites/Symbols/icon4/5_29.png",
    greenslots3_30 :  "/src/sprites/Symbols/icon4/5_30.png",
    greenslots3_31 :  "/src/sprites/Symbols/icon4/5_31.png",
    greenslots3_32 :  "/src/sprites/Symbols/icon4/5_32.png",
    greenslots3_33 :  "/src/sprites/Symbols/icon4/5_33.png",
    greenslots3_34 :  "/src/sprites/Symbols/icon4/5_34.png",
    greenslots3_35 :  "/src/sprites/Symbols/icon4/5_35.png",
    greenslots3_36 :  "/src/sprites/Symbols/icon4/5_36.png",

    redslots3_0 :  "/src/sprites/Symbols/iconred4/500.png",
    redslots3_1 :  "/src/sprites/Symbols/iconred4/501.png",
    redslots3_2 :  "/src/sprites/Symbols/iconred4/502.png",
    redslots3_3 :  "/src/sprites/Symbols/iconred4/503.png",
    redslots3_4 :  "/src/sprites/Symbols/iconred4/504.png",
    redslots3_5 :  "/src/sprites/Symbols/iconred4/505.png",
    redslots3_6 :  "/src/sprites/Symbols/iconred4/506.png",
    redslots3_7 :  "/src/sprites/Symbols/iconred4/507.png",
    redslots3_8 :  "/src/sprites/Symbols/iconred4/508.png",
    redslots3_9 :  "/src/sprites/Symbols/iconred4/509.png",
    redslots3_10 :  "/src/sprites/Symbols/iconred4/510.png",
    redslots3_11 :  "/src/sprites/Symbols/iconred4/511.png",
    redslots3_12 :  "/src/sprites/Symbols/iconred4/512.png",
    redslots3_13 :  "/src/sprites/Symbols/iconred4/513.png",
    redslots3_14 :  "/src/sprites/Symbols/iconred4/514.png",
    redslots3_15 :  "/src/sprites/Symbols/iconred4/515.png",
    redslots3_16 :  "/src/sprites/Symbols/iconred4/516.png",
    redslots3_17 :  "/src/sprites/Symbols/iconred4/517.png",
    redslots3_18 :  "/src/sprites/Symbols/iconred4/518.png",
    redslots3_19 :  "/src/sprites/Symbols/iconred4/519.png",
    redslots3_20 :  "/src/sprites/Symbols/iconred4/520.png",
    redslots3_21 :  "/src/sprites/Symbols/iconred4/521.png",
    redslots3_22 :  "/src/sprites/Symbols/iconred4/522.png",
    redslots3_23 :  "/src/sprites/Symbols/iconred4/523.png",
    redslots3_24 :  "/src/sprites/Symbols/iconred4/524.png",
    redslots3_25 :  "/src/sprites/Symbols/iconred4/525.png",
    redslots3_26 :  "/src/sprites/Symbols/iconred4/526.png",
    redslots3_27 :  "/src/sprites/Symbols/iconred4/527.png",
    redslots3_28 :  "/src/sprites/Symbols/iconred4/528.png",
    redslots3_29 :  "/src/sprites/Symbols/iconred4/529.png",
    redslots3_30 :  "/src/sprites/Symbols/iconred4/530.png",
    redslots3_31 :  "/src/sprites/Symbols/iconred4/531.png",
    redslots3_32 :  "/src/sprites/Symbols/iconred4/532.png",
    redslots3_33 :  "/src/sprites/Symbols/iconred4/533.png",
    redslots3_34 :  "/src/sprites/Symbols/iconred4/534.png",
    redslots3_35 :  "/src/sprites/Symbols/iconred4/535.png",
    redslots3_36 :  "/src/sprites/Symbols/iconred4/536.png",


    greenslots4_0 :  "/src/sprites/Symbols/icon5/10_00.png",
    greenslots4_1 :  "/src/sprites/Symbols/icon5/10_01.png",
    greenslots4_2 :  "/src/sprites/Symbols/icon5/10_02.png",
    greenslots4_3 :  "/src/sprites/Symbols/icon5/10_03.png",
    greenslots4_4 :  "/src/sprites/Symbols/icon5/10_04.png",
    greenslots4_5 :  "/src/sprites/Symbols/icon5/10_05.png",
    greenslots4_6 :  "/src/sprites/Symbols/icon5/10_06.png",
    greenslots4_7 :  "/src/sprites/Symbols/icon5/10_07.png",
    greenslots4_8 :  "/src/sprites/Symbols/icon5/10_08.png",
    greenslots4_9 :  "/src/sprites/Symbols/icon5/10_09.png",
    greenslots4_10 :  "/src/sprites/Symbols/icon5/10_10.png",
    greenslots4_11 :  "/src/sprites/Symbols/icon5/10_11.png",
    greenslots4_12 :  "/src/sprites/Symbols/icon5/10_12.png",
    greenslots4_13 :  "/src/sprites/Symbols/icon5/10_13.png",
    greenslots4_14 :  "/src/sprites/Symbols/icon5/10_14.png",
    greenslots4_15 :  "/src/sprites/Symbols/icon5/10_15.png",
    greenslots4_16 :  "/src/sprites/Symbols/icon5/10_16.png",
    greenslots4_17 :  "/src/sprites/Symbols/icon5/10_17.png",
    greenslots4_18 :  "/src/sprites/Symbols/icon5/10_18.png",
    greenslots4_19 :  "/src/sprites/Symbols/icon5/10_19.png",
    greenslots4_20 :  "/src/sprites/Symbols/icon5/10_20.png",
    greenslots4_21 :  "/src/sprites/Symbols/icon5/10_21.png",
    greenslots4_22 :  "/src/sprites/Symbols/icon5/10_22.png",
    greenslots4_23 :  "/src/sprites/Symbols/icon5/10_23.png",
    greenslots4_24 :  "/src/sprites/Symbols/icon5/10_24.png",
    greenslots4_25 :  "/src/sprites/Symbols/icon5/10_25.png",
    greenslots4_26 :  "/src/sprites/Symbols/icon5/10_26.png",
    greenslots4_27 :  "/src/sprites/Symbols/icon5/10_27.png",
    greenslots4_28 :  "/src/sprites/Symbols/icon5/10_28.png",
    greenslots4_29 :  "/src/sprites/Symbols/icon5/10_29.png",
    greenslots4_30 :  "/src/sprites/Symbols/icon5/10_30.png",
    greenslots4_31 :  "/src/sprites/Symbols/icon5/10_31.png",
    greenslots4_32 :  "/src/sprites/Symbols/icon5/10_32.png",
    greenslots4_33 :  "/src/sprites/Symbols/icon5/10_33.png",
    greenslots4_34 :  "/src/sprites/Symbols/icon5/10_34.png",
    greenslots4_35 :  "/src/sprites/Symbols/icon5/10_35.png",
    greenslots4_36 :  "/src/sprites/Symbols/icon5/10_36.png",

   redslots4_0 :  "/src/sprites/Symbols/iconred5/10_00.png",
   redslots4_1 :  "/src/sprites/Symbols/iconred5/10_01.png",
   redslots4_2 :  "/src/sprites/Symbols/iconred5/10_02.png",
   redslots4_3 :  "/src/sprites/Symbols/iconred5/10_03.png",
   redslots4_4 :  "/src/sprites/Symbols/iconred5/10_04.png",
   redslots4_5 :  "/src/sprites/Symbols/iconred5/10_05.png",
   redslots4_6 :  "/src/sprites/Symbols/iconred5/10_06.png",
   redslots4_7 :  "/src/sprites/Symbols/iconred5/10_07.png",
   redslots4_8 :  "/src/sprites/Symbols/iconred5/10_08.png",
   redslots4_9 :  "/src/sprites/Symbols/iconred5/10_09.png",
   redslots4_10 :  "/src/sprites/Symbols/iconred5/10_10.png",
   redslots4_11 :  "/src/sprites/Symbols/iconred5/10_11.png",
   redslots4_12 :  "/src/sprites/Symbols/iconred5/10_12.png",
   redslots4_13 :  "/src/sprites/Symbols/iconred5/10_13.png",
   redslots4_14 :  "/src/sprites/Symbols/iconred5/10_14.png",
   redslots4_15 :  "/src/sprites/Symbols/iconred5/10_15.png",
   redslots4_16 :  "/src/sprites/Symbols/iconred5/10_16.png",
   redslots4_17 :  "/src/sprites/Symbols/iconred5/10_17.png",
   redslots4_18 :  "/src/sprites/Symbols/iconred5/10_18.png",
   redslots4_19 :  "/src/sprites/Symbols/iconred5/10_19.png",
   redslots4_20 :  "/src/sprites/Symbols/iconred5/10_20.png",
   redslots4_21 :  "/src/sprites/Symbols/iconred5/10_21.png",
   redslots4_22 :  "/src/sprites/Symbols/iconred5/10_22.png",
   redslots4_23 :  "/src/sprites/Symbols/iconred5/10_23.png",
   redslots4_24 :  "/src/sprites/Symbols/iconred5/10_24.png",
   redslots4_25 :  "/src/sprites/Symbols/iconred5/10_25.png",
   redslots4_26 :  "/src/sprites/Symbols/iconred5/10_26.png",
   redslots4_27 :  "/src/sprites/Symbols/iconred5/10_27.png",
   redslots4_28 :  "/src/sprites/Symbols/iconred5/10_28.png",
   redslots4_29 :  "/src/sprites/Symbols/iconred5/10_29.png",
   redslots4_30 :  "/src/sprites/Symbols/iconred5/10_30.png",
   redslots4_31 :  "/src/sprites/Symbols/iconred5/10_31.png",
   redslots4_32 :  "/src/sprites/Symbols/iconred5/10_32.png",
   redslots4_33 :  "/src/sprites/Symbols/iconred5/10_33.png",
   redslots4_34 :  "/src/sprites/Symbols/iconred5/10_34.png",
   redslots4_35 :  "/src/sprites/Symbols/iconred5/10_35.png",
   redslots4_36 :  "/src/sprites/Symbols/iconred5/10_36.png",

    greenslots5_0 :  "/src/sprites/Symbols/icon6/0_00.png",
    greenslots5_1 :  "/src/sprites/Symbols/icon6/0_01.png",
    greenslots5_2 :  "/src/sprites/Symbols/icon6/0_02.png",
    greenslots5_3 :  "/src/sprites/Symbols/icon6/0_03.png",
    greenslots5_4 :  "/src/sprites/Symbols/icon6/0_04.png",
    greenslots5_5 :  "/src/sprites/Symbols/icon6/0_05.png",
    greenslots5_6 :  "/src/sprites/Symbols/icon6/0_06.png",
    greenslots5_7 :  "/src/sprites/Symbols/icon6/0_07.png",
    greenslots5_8 :  "/src/sprites/Symbols/icon6/0_08.png",
    greenslots5_9 :  "/src/sprites/Symbols/icon6/0_09.png",
    greenslots5_10 :  "/src/sprites/Symbols/icon6/0_10.png",
    greenslots5_11 :  "/src/sprites/Symbols/icon6/0_11.png",
    greenslots5_12 :  "/src/sprites/Symbols/icon6/0_12.png",
    greenslots5_13 :  "/src/sprites/Symbols/icon6/0_13.png",
    greenslots5_14 :  "/src/sprites/Symbols/icon6/0_14.png",
    greenslots5_15 :  "/src/sprites/Symbols/icon6/0_15.png",
    greenslots5_16 :  "/src/sprites/Symbols/icon6/0_16.png",
    greenslots5_17 :  "/src/sprites/Symbols/icon6/0_17.png",
    greenslots5_18 :  "/src/sprites/Symbols/icon6/0_18.png",
    greenslots5_19 :  "/src/sprites/Symbols/icon6/0_19.png",
    greenslots5_20 :  "/src/sprites/Symbols/icon6/0_20.png",
    greenslots5_21 :  "/src/sprites/Symbols/icon6/0_21.png",
    greenslots5_22 :  "/src/sprites/Symbols/icon6/0_22.png",
    greenslots5_23 :  "/src/sprites/Symbols/icon6/0_23.png",
    greenslots5_24 :  "/src/sprites/Symbols/icon6/0_24.png",
    greenslots5_25 :  "/src/sprites/Symbols/icon6/0_25.png",
    greenslots5_26 :  "/src/sprites/Symbols/icon6/0_26.png",
    greenslots5_27 :  "/src/sprites/Symbols/icon6/0_27.png",
    greenslots5_28 :  "/src/sprites/Symbols/icon6/0_28.png",
    greenslots5_29 :  "/src/sprites/Symbols/icon6/0_29.png",
    greenslots5_30 :  "/src/sprites/Symbols/icon6/0_30.png",
    greenslots5_31 :  "/src/sprites/Symbols/icon6/0_31.png",
    greenslots5_32 :  "/src/sprites/Symbols/icon6/0_32.png",
    greenslots5_33 :  "/src/sprites/Symbols/icon6/0_33.png",
    greenslots5_34 :  "/src/sprites/Symbols/icon6/0_34.png",
    greenslots5_35 :  "/src/sprites/Symbols/icon6/0_35.png",
    greenslots5_36 :  "/src/sprites/Symbols/icon6/0_36.png",

    redslots5_0 :  "/src/sprites/Symbols/iconred6/0_00.png",
    redslots5_1 :  "/src/sprites/Symbols/iconred6/0_01.png",
    redslots5_2 :  "/src/sprites/Symbols/iconred6/0_02.png",
    redslots5_3 :  "/src/sprites/Symbols/iconred6/0_03.png",
    redslots5_4 :  "/src/sprites/Symbols/iconred6/0_04.png",
    redslots5_5 :  "/src/sprites/Symbols/iconred6/0_05.png",
    redslots5_6 :  "/src/sprites/Symbols/iconred6/0_06.png",
    redslots5_7 :  "/src/sprites/Symbols/iconred6/0_07.png",
    redslots5_8 :  "/src/sprites/Symbols/iconred6/0_08.png",
    redslots5_9 :  "/src/sprites/Symbols/iconred6/0_09.png",
    redslots5_10 :  "/src/sprites/Symbols/iconred6/0_10.png",
    redslots5_11 :  "/src/sprites/Symbols/iconred6/0_11.png",
    redslots5_12 :  "/src/sprites/Symbols/iconred6/0_12.png",
    redslots5_13 :  "/src/sprites/Symbols/iconred6/0_13.png",
    redslots5_14 :  "/src/sprites/Symbols/iconred6/0_14.png",
    redslots5_15 :  "/src/sprites/Symbols/iconred6/0_15.png",
    redslots5_16 :  "/src/sprites/Symbols/iconred6/0_16.png",
    redslots5_17 :  "/src/sprites/Symbols/iconred6/0_17.png",
    redslots5_18 :  "/src/sprites/Symbols/iconred6/0_18.png",
    redslots5_19 :  "/src/sprites/Symbols/iconred6/0_19.png",
    redslots5_20 :  "/src/sprites/Symbols/iconred6/0_20.png",
    redslots5_21 :  "/src/sprites/Symbols/iconred6/0_21.png",
    redslots5_22 :  "/src/sprites/Symbols/iconred6/0_22.png",
    redslots5_23 :  "/src/sprites/Symbols/iconred6/0_23.png",
    redslots5_24 :  "/src/sprites/Symbols/iconred6/0_24.png",
    redslots5_25 :  "/src/sprites/Symbols/iconred6/0_25.png",
    redslots5_26 :  "/src/sprites/Symbols/iconred6/0_26.png",
    redslots5_27 :  "/src/sprites/Symbols/iconred6/0_27.png",
    redslots5_28 :  "/src/sprites/Symbols/iconred6/0_28.png",
    redslots5_29 :  "/src/sprites/Symbols/iconred6/0_29.png",
    redslots5_30 :  "/src/sprites/Symbols/iconred6/0_30.png",
    redslots5_31 :  "/src/sprites/Symbols/iconred6/0_31.png",
    redslots5_32 :  "/src/sprites/Symbols/iconred6/0_32.png",
    redslots5_33 :  "/src/sprites/Symbols/iconred6/0_33.png",
    redslots5_34 :  "/src/sprites/Symbols/iconred6/0_34.png",
    redslots5_35 :  "/src/sprites/Symbols/iconred6/0_35.png",
    redslots5_36 :  "/src/sprites/Symbols/iconred6/0_36.png",

    greenslots6_0 :  "/src/sprites/Symbols/icon7/00_00.png",
    greenslots6_1 :  "/src/sprites/Symbols/icon7/00_01.png",
    greenslots6_2 :  "/src/sprites/Symbols/icon7/00_02.png",
    greenslots6_3 :  "/src/sprites/Symbols/icon7/00_03.png",
    greenslots6_4 :  "/src/sprites/Symbols/icon7/00_04.png",
    greenslots6_5 :  "/src/sprites/Symbols/icon7/00_05.png",
    greenslots6_6 :  "/src/sprites/Symbols/icon7/00_06.png",
    greenslots6_7 :  "/src/sprites/Symbols/icon7/00_07.png",
    greenslots6_8 :  "/src/sprites/Symbols/icon7/00_08.png",
    greenslots6_9 :  "/src/sprites/Symbols/icon7/00_09.png",
    greenslots6_10 :  "/src/sprites/Symbols/icon7/00_10.png",
    greenslots6_11 :  "/src/sprites/Symbols/icon7/00_11.png",
    greenslots6_12 :  "/src/sprites/Symbols/icon7/00_12.png",
    greenslots6_13 :  "/src/sprites/Symbols/icon7/00_13.png",
    greenslots6_14 :  "/src/sprites/Symbols/icon7/00_14.png",
    greenslots6_15 :  "/src/sprites/Symbols/icon7/00_15.png",
    greenslots6_16 :  "/src/sprites/Symbols/icon7/00_16.png",
    greenslots6_17 :  "/src/sprites/Symbols/icon7/00_17.png",
    greenslots6_18 :  "/src/sprites/Symbols/icon7/00_18.png",
    greenslots6_19 :  "/src/sprites/Symbols/icon7/00_19.png",
    greenslots6_20 :  "/src/sprites/Symbols/icon7/00_20.png",
    greenslots6_21 :  "/src/sprites/Symbols/icon7/00_21.png",
    greenslots6_22 :  "/src/sprites/Symbols/icon7/00_22.png",
    greenslots6_23 :  "/src/sprites/Symbols/icon7/00_23.png",
    greenslots6_24 :  "/src/sprites/Symbols/icon7/00_24.png",
    greenslots6_25 :  "/src/sprites/Symbols/icon7/00_25.png",
    greenslots6_26 :  "/src/sprites/Symbols/icon7/00_26.png",
    greenslots6_27 :  "/src/sprites/Symbols/icon7/00_27.png",
    greenslots6_28 :  "/src/sprites/Symbols/icon7/00_28.png",
    greenslots6_29 :  "/src/sprites/Symbols/icon7/00_29.png",
    greenslots6_30 :  "/src/sprites/Symbols/icon7/00_30.png",
    greenslots6_31 :  "/src/sprites/Symbols/icon7/00_31.png",
    greenslots6_32 :  "/src/sprites/Symbols/icon7/00_32.png",
    greenslots6_33 :  "/src/sprites/Symbols/icon7/00_33.png",
    greenslots6_34 :  "/src/sprites/Symbols/icon7/00_34.png",
    greenslots6_35 :  "/src/sprites/Symbols/icon7/00_35.png",
    greenslots6_36 :  "/src/sprites/Symbols/icon7/00_36.png",

    redslots6_0 :  "/src/sprites/Symbols/iconred7/00_00.png",
    redslots6_1 :  "/src/sprites/Symbols/iconred7/00_01.png",
    redslots6_2 :  "/src/sprites/Symbols/iconred7/00_02.png",
    redslots6_3 :  "/src/sprites/Symbols/iconred7/00_03.png",
    redslots6_4 :  "/src/sprites/Symbols/iconred7/00_04.png",
    redslots6_5 :  "/src/sprites/Symbols/iconred7/00_05.png",
    redslots6_6 :  "/src/sprites/Symbols/iconred7/00_06.png",
    redslots6_7 :  "/src/sprites/Symbols/iconred7/00_07.png",
    redslots6_8 :  "/src/sprites/Symbols/iconred7/00_08.png",
    redslots6_9 :  "/src/sprites/Symbols/iconred7/00_09.png",
    redslots6_10 :  "/src/sprites/Symbols/iconred7/00_10.png",
    redslots6_11 :  "/src/sprites/Symbols/iconred7/00_11.png",
    redslots6_12 :  "/src/sprites/Symbols/iconred7/00_12.png",
    redslots6_13 :  "/src/sprites/Symbols/iconred7/00_13.png",
    redslots6_14 :  "/src/sprites/Symbols/iconred7/00_14.png",
    redslots6_15 :  "/src/sprites/Symbols/iconred7/00_15.png",
    redslots6_16 :  "/src/sprites/Symbols/iconred7/00_16.png",
    redslots6_17 :  "/src/sprites/Symbols/iconred7/00_17.png",
    redslots6_18 :  "/src/sprites/Symbols/iconred7/00_18.png",
    redslots6_19 :  "/src/sprites/Symbols/iconred7/00_19.png",
    redslots6_20 :  "/src/sprites/Symbols/iconred7/00_20.png",
    redslots6_21 :  "/src/sprites/Symbols/iconred7/00_21.png",
    redslots6_22 :  "/src/sprites/Symbols/iconred7/00_22.png",
    redslots6_23 :  "/src/sprites/Symbols/iconred7/00_23.png",
    redslots6_24 :  "/src/sprites/Symbols/iconred7/00_24.png",
    redslots6_25 :  "/src/sprites/Symbols/iconred7/00_25.png",
    redslots6_26 :  "/src/sprites/Symbols/iconred7/00_26.png",
    redslots6_27 :  "/src/sprites/Symbols/iconred7/00_27.png",
    redslots6_28 :  "/src/sprites/Symbols/iconred7/00_28.png",
    redslots6_29 :  "/src/sprites/Symbols/iconred7/00_29.png",
    redslots6_30 :  "/src/sprites/Symbols/iconred7/00_30.png",
    redslots6_31 :  "/src/sprites/Symbols/iconred7/00_31.png",
    redslots6_32 :  "/src/sprites/Symbols/iconred7/00_32.png",
    redslots6_33 :  "/src/sprites/Symbols/iconred7/00_33.png",
    redslots6_34 :  "/src/sprites/Symbols/iconred7/00_34.png",
    redslots6_35 :  "/src/sprites/Symbols/iconred7/00_35.png",
    redslots6_36 :  "/src/sprites/Symbols/iconred7/00_36.png",


    greenrespin0: "src/sprites/greenrespin00.png",
    greenrespin1: "src/sprites/greenrespin01.png",
    greenrespin2: "src/sprites/greenrespin02.png", 
    greenrespin3: "src/sprites/greenrespin03.png", 
    greenrespin4: "src/sprites/greenrespin04.png", 
    greenrespin5: "src/sprites/greenrespin05.png", 
    greenrespin6: "src/sprites/greenrespin06.png", 
    greenrespin7: "src/sprites/greenrespin07.png", 
    greenrespin8: "src/sprites/greenrespin08.png",
    greenrespin9: "src/sprites/greenrespin09.png",
    greenrespin10: "src/sprites/greenrespin10.png",
    greenrespin11: "src/sprites/greenrespin11.png",
    greenrespin12: "src/sprites/greenrespin12.png", 
    greenrespin13: "src/sprites/greenrespin13.png",
    greenrespin14: "src/sprites/greenrespin14.png",
    greenrespin15: "src/sprites/greenrespin15.png",
    greenrespin16: "src/sprites/greenrespin16.png",
    greenrespin17: "src/sprites/greenrespin17.png",
    greenrespin18: "src/sprites/greenrespin18.png",
    greenrespin19: "src/sprites/greenrespin19.png",
    greenrespin20: "src/sprites/greenrespin20.png",
    greenrespin21: "src/sprites/greenrespin21.png", 
    greenrespin22: "src/sprites/greenrespin22.png",
    greenrespin23: "src/sprites/greenrespin23.png", 
    greenrespin24: "src/sprites/greenrespin24.png",
    greenrespin25: "src/sprites/greenrespin25.png",
    greenrespin26: "src/sprites/greenrespin26.png",
    greenrespin27: "src/sprites/greenrespin27.png",
    greenrespin28: "src/sprites/greenrespin28.png",
    greenrespin29: "src/sprites/greenrespin29.png",
    greenrespin30: "src/sprites/greenrespin30.png",
    greenrespin31: "src/sprites/greenrespin31.png",
    greenrespin32: "src/sprites/greenrespin32.png",
    greenrespin33: "src/sprites/greenrespin33.png",
    greenrespin34: "src/sprites/greenrespin34.png",
    greenrespin35: "src/sprites/greenrespin35.png",
    greenrespin36: "src/sprites/greenrespin36.png",
    greenrespin37: "src/sprites/greenrespin37.png",
    greenrespin38: "src/sprites/greenrespin38.png",
    greenrespin39: "src/sprites/greenrespin39.png",
    greenrespin40: "src/sprites/greenrespin40.png",
    greenrespin41: "src/sprites/greenrespin41.png",
    greenrespin42: "src/sprites/greenrespin42.png", 
    greenrespin43: "src/sprites/greenrespin43.png",
    greenrespin44: "src/sprites/greenrespin44.png",
    greenrespin45: "src/sprites/greenrespin45.png",
    greenrespin46: "src/sprites/greenrespin46.png",
    greenrespin47: "src/sprites/greenrespin47.png",
    greenrespin48: "src/sprites/greenrespin48.png",
    greenrespin49: "src/sprites/greenrespin49.png",
    greenrespin50: "src/sprites/greenrespin50.png",
    greenrespin51: "src/sprites/greenrespin51.png",
    greenrespin52: "src/sprites/greenrespin52.png",
    greenrespin53: "src/sprites/greenrespin53.png",
    greenrespin54: "src/sprites/greenrespin54.png",
    greenrespin55: "src/sprites/greenrespin55.png",
    greenrespin56: "src/sprites/greenrespin56.png",
    greenrespin57: "src/sprites/greenrespin57.png",
    greenrespin58: "src/sprites/greenrespin58.png",
    greenrespin59: "src/sprites/greenrespin59.png",

    redrespin0: "src/sprites/redrespin00.png",
    redrespin1: "src/sprites/redrespin01.png",
    redrespin2: "src/sprites/redrespin02.png", 
    redrespin3: "src/sprites/redrespin03.png", 
    redrespin4: "src/sprites/redrespin04.png", 
    redrespin5: "src/sprites/redrespin05.png", 
    redrespin6: "src/sprites/redrespin06.png", 
    redrespin7: "src/sprites/redrespin07.png", 
    redrespin8: "src/sprites/redrespin08.png",
    redrespin9: "src/sprites/redrespin09.png",
    redrespin10: "src/sprites/redrespin10.png",
    redrespin11: "src/sprites/redrespin11.png",
    redrespin12: "src/sprites/redrespin12.png", 
    redrespin13: "src/sprites/redrespin13.png",
    redrespin14: "src/sprites/redrespin14.png",
    redrespin15: "src/sprites/redrespin15.png",
    redrespin16: "src/sprites/redrespin16.png",
    redrespin17: "src/sprites/redrespin17.png",
    redrespin18: "src/sprites/redrespin18.png",
    redrespin19: "src/sprites/redrespin19.png",
    redrespin20: "src/sprites/redrespin20.png",
    redrespin21: "src/sprites/redrespin21.png", 
    redrespin22: "src/sprites/redrespin22.png",
    redrespin23: "src/sprites/redrespin23.png", 
    redrespin24: "src/sprites/redrespin24.png",
    redrespin25: "src/sprites/redrespin25.png",
    redrespin26: "src/sprites/redrespin26.png",
    redrespin27: "src/sprites/redrespin27.png",
    redrespin28: "src/sprites/redrespin28.png",
    redrespin29: "src/sprites/redrespin29.png",
    redrespin30: "src/sprites/redrespin30.png",
    redrespin31: "src/sprites/redrespin31.png",
    redrespin32: "src/sprites/redrespin32.png",
    redrespin33: "src/sprites/redrespin33.png",
    redrespin34: "src/sprites/redrespin34.png",
    redrespin35: "src/sprites/redrespin35.png",
    redrespin36: "src/sprites/redrespin36.png",
    redrespin37: "src/sprites/redrespin37.png",
    redrespin38: "src/sprites/redrespin38.png",
    redrespin39: "src/sprites/redrespin39.png",
    redrespin40: "src/sprites/redrespin40.png",
    redrespin41: "src/sprites/redrespin41.png",
    redrespin42: "src/sprites/redrespin42.png", 
    redrespin43: "src/sprites/redrespin43.png",
    redrespin44: "src/sprites/redrespin44.png",
    redrespin45: "src/sprites/redrespin45.png",
    redrespin46: "src/sprites/redrespin46.png",

    nicewin1: "src/sprites/nicewin015.png",
    nicewin2: "src/sprites/nicewin016.png",
    nicewin3: "src/sprites/nicewin017.png",
    nicewin4: "src/sprites/nicewin018.png",
    nicewin5: "src/sprites/nicewin019.png",
    nicewin6: "src/sprites/nicewin020.png",
    nicewin7: "src/sprites/nicewin021.png",
    nicewin8: "src/sprites/nicewin022.png",
    nicewin9: "src/sprites/nicewin023.png",
    nicewin10: "src/sprites/nicewin024.png",
    nicewin11: "src/sprites/nicewin025.png",
    nicewin12: "src/sprites/nicewin026.png",
    nicewin13: "src/sprites/nicewin027.png",
    nicewin14: "src/sprites/nicewin028.png",
    nicewin15: "src/sprites/nicewin029.png",
    nicewin16: "src/sprites/nicewin030.png",
    nicewin17: "src/sprites/nicewin031.png",
    nicewin18: "src/sprites/nicewin032.png",
    nicewin19: "src/sprites/nicewin033.png",
    nicewin20: "src/sprites/nicewin034.png",
    nicewin21: "src/sprites/nicewin035.png",
    nicewin22: "src/sprites/nicewin036.png",
    nicewin23: "src/sprites/nicewin037.png",
    nicewin24: "src/sprites/nicewin038.png",
    nicewin25: "src/sprites/nicewin039.png",
    nicewin26: "src/sprites/nicewin040.png",
    nicewin27: "src/sprites/nicewin041.png",
    nicewin28: "src/sprites/nicewin042.png",
    nicewin29: "src/sprites/nicewin043.png",
    nicewin30: "src/sprites/nicewin044.png",
    nicewin31: "src/sprites/nicewin045.png",
    nicewin32: "src/sprites/nicewin046.png",
    nicewin33: "src/sprites/nicewin047.png",
    nicewin34: "src/sprites/nicewin048.png",
    nicewin35: "src/sprites/nicewin049.png",
    nicewin36: "src/sprites/nicewin050.png",
    nicewin37: "src/sprites/nicewin051.png",
    nicewin38: "src/sprites/nicewin052.png",
    nicewin39: "src/sprites/nicewin053.png",
    nicewin40: "src/sprites/nicewin054.png",
    nicewin41: "src/sprites/nicewin055.png",
    nicewin42: "src/sprites/nicewin056.png",
    nicewin43: "src/sprites/nicewin057.png",
    nicewin44: "src/sprites/nicewin058.png",
    nicewin45: "src/sprites/nicewin059.png",
    nicewin46: "src/sprites/nicewin060.png",
    nicewin47: "src/sprites/nicewin061.png",
    nicewin48: "src/sprites/nicewin062.png",
    nicewin49: "src/sprites/nicewin063.png",
    nicewin50: "src/sprites/nicewin064.png",
    nicewin51: "src/sprites/nicewin065.png",
    nicewin52: "src/sprites/nicewin066.png",
    nicewin53: "src/sprites/nicewin067.png",
    nicewin54: "src/sprites/nicewin068.png",
    nicewin55: "src/sprites/nicewin069.png",
    nicewin56: "src/sprites/nicewin071.png",
    nicewin57: "src/sprites/nicewin072.png",
    nicewin58: "src/sprites/nicewin072.png",
    nicewin59: "src/sprites/nicewin073.png",
    nicewin60: "src/sprites/nicewin074.png",
    nicewin61: "src/sprites/nicewin075.png",
    nicewin62: "src/sprites/nicewin076.png",
    nicewin63: "src/sprites/nicewin077.png",
    nicewin64: "src/sprites/nicewin078.png",
    nicewin65: "src/sprites/nicewin079.png",
    nicewin66: "src/sprites/nicewin080.png",
    nicewin67: "src/sprites/nicewin081.png",
    nicewin68: "src/sprites/nicewin082.png",
    nicewin69: "src/sprites/nicewin083.png",
    nicewin70: "src/sprites/nicewin084.png",
    nicewin71: "src/sprites/nicewin085.png",
    nicewin72: "src/sprites/nicewin086.png",
    nicewin73: "src/sprites/nicewin087.png",
    nicewin74: "src/sprites/nicewin088.png",
    nicewin75: "src/sprites/nicewin089.png",
    nicewin76: "src/sprites/nicewin090.png",
    nicewin77: "src/sprites/nicewin091.png",
    nicewin78: "src/sprites/nicewin092.png",
    nicewin79: "src/sprites/nicewin093.png",
    nicewin80: "src/sprites/nicewin094.png",
    nicewin81: "src/sprites/nicewin095.png",
    nicewin82: "src/sprites/nicewin096.png",
    nicewin83: "src/sprites/nicewin097.png",
    nicewin84: "src/sprites/nicewin098.png",
    nicewin85: "src/sprites/nicewin099.png",
    nicewin86: "src/sprites/nicewin100.png",
    nicewin87: "src/sprites/nicewin101.png",
    nicewin88: "src/sprites/nicewin102.png",
    nicewin89: "src/sprites/nicewin103.png",
    nicewin90: "src/sprites/nicewin104.png",
    nicewin91: "src/sprites/nicewin105.png",
    nicewin92: "src/sprites/nicewin106.png",
    nicewin93: "src/sprites/nicewin107.png",
    nicewin94: "src/sprites/nicewin108.png",
    nicewin95: "src/sprites/nicewin109.png",
    nicewin96: "src/sprites/nicewin110.png",
    nicewin97: "src/sprites/nicewin111.png",
    nicewin98: "src/sprites/nicewin112.png",
    nicewin99: "src/sprites/nicewin113.png",
    nicewin100: "src/sprites/nicewin114.png",
    nicewin101: "src/sprites/nicewin115.png",
    nicewin102: "src/sprites/nicewin116.png",
    nicewin103: "src/sprites/nicewin117.png",
    nicewin104: "src/sprites/nicewin118.png",
    nicewin105: "src/sprites/nicewin119.png",
    nicewin106: "src/sprites/nicewin120.png",
    nicewin107: "src/sprites/nicewin121.png",
    nicewin108: "src/sprites/nicewin122.png",
    nicewin109: "src/sprites/nicewin123.png",
    nicewin110: "src/sprites/nicewin124.png",
    nicewin111: "src/sprites/nicewin125.png",
    nicewin112: "src/sprites/nicewin126.png",
    nicewin113: "src/sprites/nicewin127.png",
    nicewin114: "src/sprites/nicewin128.png",
    nicewin115: "src/sprites/nicewin129.png",
    nicewin116: "src/sprites/nicewin130.png",
    nicewin117: "src/sprites/nicewin131.png",
    nicewin118: "src/sprites/nicewin132.png",
    nicewin119: "src/sprites/nicewin133.png",
    nicewin120: "src/sprites/nicewin134.png",
    nicewin121: "src/sprites/nicewin135.png",
    nicewin122: "src/sprites/nicewin136.png",
    nicewin123: "src/sprites/nicewin137.png",
    nicewin124: "src/sprites/nicewin138.png",
    nicewin125: "src/sprites/nicewin139.png",
    nicewin126: "src/sprites/nicewin140.png",
    nicewin127: "src/sprites/nicewin141.png",
    nicewin128: "src/sprites/nicewin142.png",
    nicewin129: "src/sprites/nicewin143.png",
    nicewin130: "src/sprites/nicewin144.png",
    nicewin131: "src/sprites/nicewin145.png",
    nicewin132: "src/sprites/nicewin146.png",
    nicewin133: "src/sprites/nicewin147.png",
    nicewin134: "src/sprites/nicewin148.png",
    nicewin135: "src/sprites/nicewin149.png",
    nicewin136: "src/sprites/nicewin150.png",
    nicewin137: "src/sprites/nicewin151.png",
}

export const staticData = {
    Background:  "src/sprites/Background.jpg",
};

export const fontData = {
    crashLandingItalic : "src/fonts/CrashLandingBB.ttf"
}

export const LoaderSoundConfig: any = {
        backgroundMusic: "src/sounds/Teaser.mp3",
        onSpin :  "/src/sounds/slot-machine-loop.mp3",
        spinButton: "src/sounds/spin.wav",
        winMusic: "src/sounds/JackpotWinner.mp3",
        buttonpressed: "src/sounds/Game-Button.wav",
        bonusBg: "src/sounds/bonusbg.mp3",
        bonuswin: "src/sounds/bonuswin.mp3",
 
};
