export const LoaderConfig = {

    greenCircle: "src/sprites/Green-Circle.png",
    redCircle:"src/sprites/Red-Circle.png",

    greenBackground: "src/sprites/greenBg.jpg",
    redBackground: "src/sprites/redBg.jpg",
    greenRightBorder: "src/sprites/greenRightBorder.png",
    greenLeftBorder: "src/sprites/greenLeftborder.png",
    redRightBorder: "src/sprites/redRightBorder.png",
    redLeftBorder: "src/sprites/redLeftborder.png",

    greenHead: "src/sprites/greenHead.png",
    redHead: "src/sprites/redHead.png",

    greenLogo: "src/sprites/cash-machine-logo.png",
    redLogo: "src/sprites/redcash-machine-logo.png",
    taskBar: "src/sprites/taskBar.png",
    greenCentreFrame: "src/sprites/greenCentreFrame.png",
    whatUSeeText: "src/sprites/winwhatuSeeText.png",
    slotBg: "src/Sprites/SlotBg.png",


    spinBtn : "/src/sprites/ButtonSpin_1.png",
    spinBtnOnPressed :  "/src/sprites/ButtonSpinHover_1.png",
    maxBetBtn :  "/src/sprites/ButtonMaxBet_1.png",
    maxBetBtOnPressed :  "/src/sprites/ButtonMaxBetHover_1.png",
    autoSpin :  "/src/sprites/ButtonAutoSpin_1.png",
    autoSpinOnPressed : "/src/sprites/ButtonAutoSpinHover_1.png",
    pBtn  :  "/src/sprites/ButtonPlus.png",
    pBtnH  :  "/src/sprites/ButtonPlusHover.png",
    lines :  "/src/sprites/PanelLines.png",
    GambleBg: "src/sprites/GambleBg.png",
    winPanel :  "/src/sprites/PanelWin.png",
    winPanel1:  "/src/sprites/PanelWin1.png",  
    bonusLogo: "src/sprites/BonusLogo.png",
    riskLogo: "src/sprites/RiskLogo.png",      
    balancePanel :  "/src/sprites/PanelBalance.png",
    MenuBtn :  "/src/sprites/ButtonMenu.png",
    MenuBtnH :  "/src/sprites/ButtonMenuHover.png",
    settingBtn :  "/src/sprites/ButtonSettings.png",
    settingBtnH :  "/src/sprites/ButtonSettingsHover.png",
    infoBtn :  "/src/sprites/ButtonInfo.png",
    infoBtnH :  "/src/sprites/ButtonInfoHover.png",

    inofIcon1: "src/sprites/info1.png",
    inofIcon2: "src/sprites/info2.png",
    inofIcon3: "src/sprites/info3.png",
    inofIcon4: "src/sprites/info4.png",
    inofIcon5: "src/sprites/info5.png",
    inofIcon6: "src/sprites/info6.png",
    inofIcon7: "src/sprites/info7.png",
    inofIcon8: "src/sprites/info8.png",

    exitButton: "src/sprites/ExitButton.png",
    exitButtonPressed: "src/sprites/ExitButton.png",
    PopupBackground: "src/sprites/popupBackground.png",
    messagePopup: "src/sprites/messagePopup.png",
    hugeWinPopup:"src/sprites/HugeWinPopup.png",
    megaWinPopup: "src/sprites/MegaWinPopup.png",
    leftArrow: "src/sprites/leftArrow.png",
    rightArrow: "src/sprites/RightArrow.png",
    infoCross: "src/sprites/infoCross.png",
    disconnectClose: "src/sprites/closeButton.png",
    // BonusScenegame: "src/sprites/BonusSceneImage.jpg",
    // riskGameimage: "src/sprites/RiskGameImage.jpg",

 
    soundImage:"src/sprites/Sounds.png",
    musicImage: "src/sprites/Music.png",
    yesButton:"src/sprites/yesButton.png",
    yesButtonHover: "src/sprites/yesButtonHover.png",
    noButton:"src/sprites/noButton.png",
    noButtonHover:"src/sprites/noButtonHover.png",
    sounProgress: "src/sprites/soundProgreesBar.png",
    soundIndicator: "src/sprites/Indicator.png",
    indicatorSprite: "src/sprites/SliderButton.png",

    left0: "src/sprites/1.png",
    left1: "src/sprites/2.png",
    left2: "src/sprites/3.png",
    left3: "src/sprites/4.png",
    left4: "src/sprites/5.png",
    left5: "src/sprites/6.png",
    left6: "src/sprites/7.png",
    left7: "src/sprites/8.png",
    left8: "src/sprites/9.png",

    leftHover0: "src/sprites/LineNumber1.png",
    leftHover1: "src/sprites/LineNumber2.png",
    leftHover2: "src/sprites/LineNumber3.png",
    leftHover3: "src/sprites/LineNumber4.png",
    leftHover4: "src/sprites/LineNumber5.png",
    leftHover5: "src/sprites/LineNumber6.png",
    leftHover6: "src/sprites/LineNumber7.png",
    leftHover7: "src/sprites/LineNumber8.png",
    leftHover8: "src/sprites/LineNumber9.png",

    right0: "src/sprites/1.png",
    right1: "src/sprites/2.png",
    right2: "src/sprites/3.png",
    right3: "src/sprites/4.png",
    right4: "src/sprites/5.png",
    right5: "src/sprites/6.png",
    right6: "src/sprites/7.png",
    right7: "src/sprites/8.png",
    right8: "src/sprites/9.png",

    rightHover0: "src/sprites/LineNumber1.png",
    rightHover1: "src/sprites/LineNumber2.png",
    rightHover2: "src/sprites/LineNumber3.png",
    rightHover3: "src/sprites/LineNumber4.png",
    rightHover4: "src/sprites/LineNumber5.png",
    rightHover5: "src/sprites/LineNumber6.png",
    rightHover6: "src/sprites/LineNumber7.png",
    rightHover7: "src/sprites/LineNumber8.png",
    rightHover8: "src/sprites/LineNumber9.png",


    greenslots0_0 :  "/src/sprites/Symbols/icon1/slots1_0.png",
    greenslots0_1: "/src/sprites/Symbols/icon1/slots1_1.png",
    greenslots0_2: "/src/sprites/Symbols/icon1/slots1_2.png",
    //red
    redslots0_0 :  "/src/sprites/Symbols/iconred1/slots1_0.png",
    redslots0_1: "/src/sprites/Symbols/iconred1/slots1_1.png",
    redslots0_2: "/src/sprites/Symbols/iconred1/slots1_2.png",

    greenslots1_0 :  "/src/sprites/Symbols/icon2/1_00.png",
    greenslots1_1 :  "/src/sprites/Symbols/icon2/1_01.png",
    greenslots1_2 :  "/src/sprites/Symbols/icon2/1_02.png",
    greenslots1_3 :  "/src/sprites/Symbols/icon2/1_03.png",
    greenslots1_4 :  "/src/sprites/Symbols/icon2/1_04.png",
    greenslots1_5 :  "/src/sprites/Symbols/icon2/1_05.png",
    greenslots1_6 :  "/src/sprites/Symbols/icon2/1_06.png",
    greenslots1_7 :  "/src/sprites/Symbols/icon2/1_07.png",
    greenslots1_8 :  "/src/sprites/Symbols/icon2/1_08.png",
    greenslots1_9 :  "/src/sprites/Symbols/icon2/1_09.png",
    greenslots1_10 :  "/src/sprites/Symbols/icon2/1_10.png",
    greenslots1_11 :  "/src/sprites/Symbols/icon2/1_11.png",
    greenslots1_12 :  "/src/sprites/Symbols/icon2/1_12.png",
    greenslots1_13 :  "/src/sprites/Symbols/icon2/1_13.png",
    greenslots1_14 :  "/src/sprites/Symbols/icon2/1_14.png",
    greenslots1_15 :  "/src/sprites/Symbols/icon2/1_15.png",
    greenslots1_16 :  "/src/sprites/Symbols/icon2/1_16.png",
    greenslots1_17 :  "/src/sprites/Symbols/icon2/1_17.png",
    greenslots1_18 :  "/src/sprites/Symbols/icon2/1_18.png",
    greenslots1_19 :  "/src/sprites/Symbols/icon2/1_19.png",
    greenslots1_20 :  "/src/sprites/Symbols/icon2/1_20.png",
    greenslots1_21 :  "/src/sprites/Symbols/icon2/1_21.png",
    greenslots1_22 :  "/src/sprites/Symbols/icon2/1_22.png",
    greenslots1_23 :  "/src/sprites/Symbols/icon2/1_23.png",
    greenslots1_24 :  "/src/sprites/Symbols/icon2/1_24.png",
    greenslots1_25 :  "/src/sprites/Symbols/icon2/1_25.png",
    greenslots1_26 :  "/src/sprites/Symbols/icon2/1_26.png",
    greenslots1_27 :  "/src/sprites/Symbols/icon2/1_27.png",
    greenslots1_28 :  "/src/sprites/Symbols/icon2/1_28.png",
    greenslots1_29 :  "/src/sprites/Symbols/icon2/1_29.png",
    greenslots1_30 :  "/src/sprites/Symbols/icon2/1_30.png",
    greenslots1_31 :  "/src/sprites/Symbols/icon2/1_31.png",
    greenslots1_32 :  "/src/sprites/Symbols/icon2/1_32.png",
    greenslots1_33 :  "/src/sprites/Symbols/icon2/1_33.png",
    greenslots1_34 :  "/src/sprites/Symbols/icon2/1_34.png",
    greenslots1_35 :  "/src/sprites/Symbols/icon2/1_35.png",
    greenslots1_36 :  "/src/sprites/Symbols/icon2/1_36.png",

    redslots1_0 :  "/src/sprites/Symbols/iconred2/1_00.png",
    redslots1_1 :  "/src/sprites/Symbols/iconred2/1_01.png",
    redslots1_2 :  "/src/sprites/Symbols/iconred2/1_02.png",
    redslots1_3 :  "/src/sprites/Symbols/iconred2/1_03.png",
    redslots1_4 :  "/src/sprites/Symbols/iconred2/1_04.png",
    redslots1_5 :  "/src/sprites/Symbols/iconred2/1_05.png",
    redslots1_6 :  "/src/sprites/Symbols/iconred2/1_06.png",
    redslots1_7 :  "/src/sprites/Symbols/iconred2/1_07.png",
    redslots1_8 :  "/src/sprites/Symbols/iconred2/1_08.png",
    redslots1_9 :  "/src/sprites/Symbols/iconred2/1_09.png",
    redslots1_10 :  "/src/sprites/Symbols/iconred2/1_10.png",
    redslots1_11 :  "/src/sprites/Symbols/iconred2/1_11.png",
    redslots1_12 :  "/src/sprites/Symbols/iconred2/1_12.png",
    redslots1_13 :  "/src/sprites/Symbols/iconred2/1_13.png",
    redslots1_14 :  "/src/sprites/Symbols/iconred2/1_14.png",
    redslots1_15 :  "/src/sprites/Symbols/iconred2/1_15.png",
    redslots1_16 :  "/src/sprites/Symbols/iconred2/1_16.png",
    redslots1_17 :  "/src/sprites/Symbols/iconred2/1_17.png",
    redslots1_18 :  "/src/sprites/Symbols/iconred2/1_18.png",
    redslots1_19 :  "/src/sprites/Symbols/iconred2/1_19.png",
    redslots1_20 :  "/src/sprites/Symbols/iconred2/1_20.png",
    redslots1_21 :  "/src/sprites/Symbols/iconred2/1_21.png",
    redslots1_22 :  "/src/sprites/Symbols/iconred2/1_22.png",
    redslots1_23 :  "/src/sprites/Symbols/iconred2/1_23.png",
    redslots1_24 :  "/src/sprites/Symbols/iconred2/1_24.png",
    redslots1_25 :  "/src/sprites/Symbols/iconred2/1_25.png",
    redslots1_26 :  "/src/sprites/Symbols/iconred2/1_26.png",
    redslots1_27 :  "/src/sprites/Symbols/iconred2/1_27.png",
    redslots1_28 :  "/src/sprites/Symbols/iconred2/1_28.png",
    redslots1_29 :  "/src/sprites/Symbols/iconred2/1_29.png",
    redslots1_30 :  "/src/sprites/Symbols/iconred2/1_30.png",
    redslots1_31 :  "/src/sprites/Symbols/iconred2/1_31.png",
    redslots1_32 :  "/src/sprites/Symbols/iconred2/1_32.png",
    redslots1_33 :  "/src/sprites/Symbols/iconred2/1_33.png",
    redslots1_34 :  "/src/sprites/Symbols/iconred2/1_34.png",
    redslots1_35 :  "/src/sprites/Symbols/iconred2/1_35.png",
    redslots1_36 :  "/src/sprites/Symbols/iconred2/1_36.png",

    greenslots2_0 :  "/src/sprites/Symbols/icon3/2_00.png",
    greenslots2_1 :  "/src/sprites/Symbols/icon3/2_01.png",
    greenslots2_2 :  "/src/sprites/Symbols/icon3/2_02.png",
    greenslots2_3 :  "/src/sprites/Symbols/icon3/2_03.png",
    greenslots2_4 :  "/src/sprites/Symbols/icon3/2_04.png",
    greenslots2_5 :  "/src/sprites/Symbols/icon3/2_05.png",
    greenslots2_6 :  "/src/sprites/Symbols/icon3/2_06.png",
    greenslots2_7 :  "/src/sprites/Symbols/icon3/2_07.png",
    greenslots2_8 :  "/src/sprites/Symbols/icon3/2_08.png",
    greenslots2_9 :  "/src/sprites/Symbols/icon3/2_09.png",
    greenslots2_10 :  "/src/sprites/Symbols/icon3/2_10.png",
    greenslots2_11 :  "/src/sprites/Symbols/icon3/2_11.png",
    greenslots2_12 :  "/src/sprites/Symbols/icon3/2_12.png",
    greenslots2_13 :  "/src/sprites/Symbols/icon3/2_13.png",
    greenslots2_14 :  "/src/sprites/Symbols/icon3/2_14.png",
    greenslots2_15 :  "/src/sprites/Symbols/icon3/2_15.png",
    greenslots2_16 :  "/src/sprites/Symbols/icon3/2_16.png",
    greenslots2_17 :  "/src/sprites/Symbols/icon3/2_17.png",
    greenslots2_18 :  "/src/sprites/Symbols/icon3/2_18.png",
    greenslots2_19 :  "/src/sprites/Symbols/icon3/2_19.png",
    greenslots2_20 :  "/src/sprites/Symbols/icon3/2_20.png",
    greenslots2_21 :  "/src/sprites/Symbols/icon3/2_21.png",
    greenslots2_22 :  "/src/sprites/Symbols/icon3/2_22.png",
    greenslots2_23 :  "/src/sprites/Symbols/icon3/2_23.png",
    greenslots2_24 :  "/src/sprites/Symbols/icon3/2_24.png",
    greenslots2_25 :  "/src/sprites/Symbols/icon3/2_25.png",
    greenslots2_26 :  "/src/sprites/Symbols/icon3/2_26.png",
    greenslots2_27 :  "/src/sprites/Symbols/icon3/2_27.png",
    greenslots2_28 :  "/src/sprites/Symbols/icon3/2_28.png",
    greenslots2_29 :  "/src/sprites/Symbols/icon3/2_29.png",
    greenslots2_30 :  "/src/sprites/Symbols/icon3/2_30.png",
    greenslots2_31 :  "/src/sprites/Symbols/icon3/2_31.png",
    greenslots2_32 :  "/src/sprites/Symbols/icon3/2_32.png",
    greenslots2_33 :  "/src/sprites/Symbols/icon3/2_33.png",
    greenslots2_34 :  "/src/sprites/Symbols/icon3/2_34.png",
    greenslots2_35 :  "/src/sprites/Symbols/icon3/2_35.png",
    greenslots2_36 :  "/src/sprites/Symbols/icon3/2_36.png",


    greenslots3_0 :  "/src/sprites/Symbols/icon4/5_00.png",
    greenslots3_1 :  "/src/sprites/Symbols/icon4/5_01.png",
    greenslots3_2 :  "/src/sprites/Symbols/icon4/5_02.png",
    greenslots3_3 :  "/src/sprites/Symbols/icon4/5_03.png",
    greenslots3_4 :  "/src/sprites/Symbols/icon4/5_04.png",
    greenslots3_5 :  "/src/sprites/Symbols/icon4/5_05.png",
    greenslots3_6 :  "/src/sprites/Symbols/icon4/5_06.png",
    greenslots3_7 :  "/src/sprites/Symbols/icon4/5_07.png",
    greenslots3_8 :  "/src/sprites/Symbols/icon4/5_08.png",
    greenslots3_9 :  "/src/sprites/Symbols/icon4/5_09.png",
    greenslots3_10 :  "/src/sprites/Symbols/icon4/5_10.png",
    greenslots3_11 :  "/src/sprites/Symbols/icon4/5_11.png",
    greenslots3_12 :  "/src/sprites/Symbols/icon4/5_12.png",
    greenslots3_13 :  "/src/sprites/Symbols/icon4/5_13.png",
    greenslots3_14 :  "/src/sprites/Symbols/icon4/5_14.png",
    greenslots3_15 :  "/src/sprites/Symbols/icon4/5_15.png",
    greenslots3_16 :  "/src/sprites/Symbols/icon4/5_16.png",
    greenslots3_17 :  "/src/sprites/Symbols/icon4/5_17.png",
    greenslots3_18 :  "/src/sprites/Symbols/icon4/5_18.png",
    greenslots3_19 :  "/src/sprites/Symbols/icon4/5_19.png",
    greenslots3_20 :  "/src/sprites/Symbols/icon4/5_20.png",
    greenslots3_21 :  "/src/sprites/Symbols/icon4/5_21.png",
    greenslots3_22 :  "/src/sprites/Symbols/icon4/5_22.png",
    greenslots3_23 :  "/src/sprites/Symbols/icon4/5_23.png",
    greenslots3_24 :  "/src/sprites/Symbols/icon4/5_24.png",
    greenslots3_25 :  "/src/sprites/Symbols/icon4/5_25.png",
    greenslots3_26 :  "/src/sprites/Symbols/icon4/5_26.png",
    greenslots3_27 :  "/src/sprites/Symbols/icon4/5_27.png",
    greenslots3_28 :  "/src/sprites/Symbols/icon4/5_28.png",
    greenslots3_29 :  "/src/sprites/Symbols/icon4/5_29.png",
    greenslots3_30 :  "/src/sprites/Symbols/icon4/5_30.png",
    greenslots3_31 :  "/src/sprites/Symbols/icon4/5_31.png",
    greenslots3_32 :  "/src/sprites/Symbols/icon4/5_32.png",
    greenslots3_33 :  "/src/sprites/Symbols/icon4/5_33.png",
    greenslots3_34 :  "/src/sprites/Symbols/icon4/5_34.png",
    greenslots3_35 :  "/src/sprites/Symbols/icon4/5_35.png",
    greenslots3_36 :  "/src/sprites/Symbols/icon4/5_36.png",


    greenslots4_0 :  "/src/sprites/Symbols/icon5/10_00.png",
    greenslots4_1 :  "/src/sprites/Symbols/icon5/10_01.png",
    greenslots4_2 :  "/src/sprites/Symbols/icon5/10_02.png",
    greenslots4_3 :  "/src/sprites/Symbols/icon5/10_03.png",
    greenslots4_4 :  "/src/sprites/Symbols/icon5/10_04.png",
    greenslots4_5 :  "/src/sprites/Symbols/icon5/10_05.png",
    greenslots4_6 :  "/src/sprites/Symbols/icon5/10_06.png",
    greenslots4_7 :  "/src/sprites/Symbols/icon5/10_07.png",
    greenslots4_8 :  "/src/sprites/Symbols/icon5/10_08.png",
    greenslots4_9 :  "/src/sprites/Symbols/icon5/10_09.png",
    greenslots4_10 :  "/src/sprites/Symbols/icon5/10_10.png",
    greenslots4_11 :  "/src/sprites/Symbols/icon5/10_11.png",
    greenslots4_12 :  "/src/sprites/Symbols/icon5/10_12.png",
    greenslots4_13 :  "/src/sprites/Symbols/icon5/10_13.png",
    greenslots4_14 :  "/src/sprites/Symbols/icon5/10_14.png",
    greenslots4_15 :  "/src/sprites/Symbols/icon5/10_15.png",
    greenslots4_16 :  "/src/sprites/Symbols/icon5/10_16.png",
    greenslots4_17 :  "/src/sprites/Symbols/icon5/10_17.png",
    greenslots4_18 :  "/src/sprites/Symbols/icon5/10_18.png",
    greenslots4_19 :  "/src/sprites/Symbols/icon5/10_19.png",
    greenslots4_20 :  "/src/sprites/Symbols/icon5/10_20.png",
    greenslots4_21 :  "/src/sprites/Symbols/icon5/10_21.png",
    greenslots4_22 :  "/src/sprites/Symbols/icon5/10_22.png",
    greenslots4_23 :  "/src/sprites/Symbols/icon5/10_23.png",
    greenslots4_24 :  "/src/sprites/Symbols/icon5/10_24.png",
    greenslots4_25 :  "/src/sprites/Symbols/icon5/10_25.png",
    greenslots4_26 :  "/src/sprites/Symbols/icon5/10_26.png",
    greenslots4_27 :  "/src/sprites/Symbols/icon5/10_27.png",
    greenslots4_28 :  "/src/sprites/Symbols/icon5/10_28.png",
    greenslots4_29 :  "/src/sprites/Symbols/icon5/10_29.png",
    greenslots4_30 :  "/src/sprites/Symbols/icon5/10_30.png",
    greenslots4_31 :  "/src/sprites/Symbols/icon5/10_31.png",
    greenslots4_32 :  "/src/sprites/Symbols/icon5/10_32.png",
    greenslots4_33 :  "/src/sprites/Symbols/icon5/10_33.png",
    greenslots4_34 :  "/src/sprites/Symbols/icon5/10_34.png",
    greenslots4_35 :  "/src/sprites/Symbols/icon5/10_35.png",
    greenslots4_36 :  "/src/sprites/Symbols/icon5/10_36.png",

    greenslots5_0 :  "/src/sprites/Symbols/icon6/0_00.png",
    greenslots5_1 :  "/src/sprites/Symbols/icon6/0_01.png",
    greenslots5_2 :  "/src/sprites/Symbols/icon6/0_02.png",
    greenslots5_3 :  "/src/sprites/Symbols/icon6/0_03.png",
    greenslots5_4 :  "/src/sprites/Symbols/icon6/0_04.png",
    greenslots5_5 :  "/src/sprites/Symbols/icon6/0_05.png",
    greenslots5_6 :  "/src/sprites/Symbols/icon6/0_06.png",
    greenslots5_7 :  "/src/sprites/Symbols/icon6/0_07.png",
    greenslots5_8 :  "/src/sprites/Symbols/icon6/0_08.png",
    greenslots5_9 :  "/src/sprites/Symbols/icon6/0_09.png",
    greenslots5_10 :  "/src/sprites/Symbols/icon6/0_10.png",
    greenslots5_11 :  "/src/sprites/Symbols/icon6/0_11.png",
    greenslots5_12 :  "/src/sprites/Symbols/icon6/0_12.png",
    greenslots5_13 :  "/src/sprites/Symbols/icon6/0_13.png",
    greenslots5_14 :  "/src/sprites/Symbols/icon6/0_14.png",
    greenslots5_15 :  "/src/sprites/Symbols/icon6/0_15.png",
    greenslots5_16 :  "/src/sprites/Symbols/icon6/0_16.png",
    greenslots5_17 :  "/src/sprites/Symbols/icon6/0_17.png",
    greenslots5_18 :  "/src/sprites/Symbols/icon6/0_18.png",
    greenslots5_19 :  "/src/sprites/Symbols/icon6/0_19.png",
    greenslots5_20 :  "/src/sprites/Symbols/icon6/0_20.png",
    greenslots5_21 :  "/src/sprites/Symbols/icon6/0_21.png",
    greenslots5_22 :  "/src/sprites/Symbols/icon6/0_22.png",
    greenslots5_23 :  "/src/sprites/Symbols/icon6/0_23.png",
    greenslots5_24 :  "/src/sprites/Symbols/icon6/0_24.png",
    greenslots5_25 :  "/src/sprites/Symbols/icon6/0_25.png",
    greenslots5_26 :  "/src/sprites/Symbols/icon6/0_26.png",
    greenslots5_27 :  "/src/sprites/Symbols/icon6/0_27.png",
    greenslots5_28 :  "/src/sprites/Symbols/icon6/0_28.png",
    greenslots5_29 :  "/src/sprites/Symbols/icon6/0_29.png",
    greenslots5_30 :  "/src/sprites/Symbols/icon6/0_30.png",
    greenslots5_31 :  "/src/sprites/Symbols/icon6/0_31.png",
    greenslots5_32 :  "/src/sprites/Symbols/icon6/0_32.png",
    greenslots5_33 :  "/src/sprites/Symbols/icon6/0_33.png",
    greenslots5_34 :  "/src/sprites/Symbols/icon6/0_34.png",
    greenslots5_35 :  "/src/sprites/Symbols/icon6/0_35.png",
    greenslots5_36 :  "/src/sprites/Symbols/icon6/0_36.png",

    greenslots6_0 :  "/src/sprites/Symbols/icon7/00_00.png",
    greenslots6_1 :  "/src/sprites/Symbols/icon7/00_01.png",
    greenslots6_2 :  "/src/sprites/Symbols/icon7/00_02.png",
    greenslots6_3 :  "/src/sprites/Symbols/icon7/00_03.png",
    greenslots6_4 :  "/src/sprites/Symbols/icon7/00_04.png",
    greenslots6_5 :  "/src/sprites/Symbols/icon7/00_05.png",
    greenslots6_6 :  "/src/sprites/Symbols/icon7/00_06.png",
    greenslots6_7 :  "/src/sprites/Symbols/icon7/00_07.png",
    greenslots6_8 :  "/src/sprites/Symbols/icon7/00_08.png",
    greenslots6_9 :  "/src/sprites/Symbols/icon7/00_09.png",
    greenslots6_10 :  "/src/sprites/Symbols/icon7/00_10.png",
    greenslots6_11 :  "/src/sprites/Symbols/icon7/00_11.png",
    greenslots6_12 :  "/src/sprites/Symbols/icon7/00_12.png",
    greenslots6_13 :  "/src/sprites/Symbols/icon7/00_13.png",
    greenslots6_14 :  "/src/sprites/Symbols/icon7/00_14.png",
    greenslots6_15 :  "/src/sprites/Symbols/icon7/00_15.png",
    greenslots6_16 :  "/src/sprites/Symbols/icon7/00_16.png",
    greenslots6_17 :  "/src/sprites/Symbols/icon7/00_17.png",
    greenslots6_18 :  "/src/sprites/Symbols/icon7/00_18.png",
    greenslots6_19 :  "/src/sprites/Symbols/icon7/00_19.png",
    greenslots6_20 :  "/src/sprites/Symbols/icon7/00_20.png",
    greenslots6_21 :  "/src/sprites/Symbols/icon7/00_21.png",
    greenslots6_22 :  "/src/sprites/Symbols/icon7/00_22.png",
    greenslots6_23 :  "/src/sprites/Symbols/icon7/00_23.png",
    greenslots6_24 :  "/src/sprites/Symbols/icon7/00_24.png",
    greenslots6_25 :  "/src/sprites/Symbols/icon7/00_25.png",
    greenslots6_26 :  "/src/sprites/Symbols/icon7/00_26.png",
    greenslots6_27 :  "/src/sprites/Symbols/icon7/00_27.png",
    greenslots6_28 :  "/src/sprites/Symbols/icon7/00_28.png",
    greenslots6_29 :  "/src/sprites/Symbols/icon7/00_29.png",
    greenslots6_30 :  "/src/sprites/Symbols/icon7/00_30.png",
    greenslots6_31 :  "/src/sprites/Symbols/icon7/00_31.png",
    greenslots6_32 :  "/src/sprites/Symbols/icon7/00_32.png",
    greenslots6_33 :  "/src/sprites/Symbols/icon7/00_33.png",
    greenslots6_34 :  "/src/sprites/Symbols/icon7/00_34.png",
    greenslots6_35 :  "/src/sprites/Symbols/icon7/00_35.png",
    greenslots6_36 :  "/src/sprites/Symbols/icon7/00_36.png",

    megawinAnimBg: "src/sprites/rays.png",
    megawinStar: "src/sprites/stars.png",
}

export const staticData = {
    Background:  "src/sprites/Background.jpg",
};

export const fontData = {
    crashLandingItalic : "src/fonts/CrashLandingBB.ttf"
}

export const LoaderSoundConfig: any = {
        backgroundMusic: "src/sounds/Teaser.mp3",
        onSpin :  "/src/sounds/slot-machine-loop.mp3",
        spinButton: "src/sounds/spin.wav",
        winMusic: "src/sounds/JackpotWinner.wav",
        buttonpressed: "src/sounds/Game-Button.wav",
        bonusBg: "src/sounds/bonusbg.mp3",
        bonuswin: "src/sounds/bonuswin.mp3",
 
};
